#!/bin/bash

set -e -u

cd $(dirname $0)

filter="$(echo "$@" | tr ' ' '|')"
if [ -z "$filter" ]; then
  filter="."
fi

for df in $(find . -name Dockerfile | ag "$filter"); do
  dir=$(dirname $df)
  name=concourse/test-image-$(basename $dir)
  echo "building $dir as $name"
  docker build -t $name $dir
  echo "pushing"
  docker push $name
done
